# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a61deafa973c041cc8e71cd810083994ea9580788cf4151843bb1df8abc1c0e22d0c04222e518b0a70ce9ea0ba21570754e30f0e0a6287a8cb985cbcc92d8a57

test:
  secret_key_base: d69322e4400dd4508c7a25b418fc888f4360f87a5ab94d4965ec64b61f6a72ac0b7f94ea01dd8964ed27062655d65c13a92c5ca319dad7d03fa14a4b1f459ba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
